spring:
  application:
    name: product-service
  config:
    import: configserver:http://localhost:9000/
management:
  endpoints:
    web:
      exposure:
        include: prometheus
# trace all request with zipkin brave
  tracing:
    sampling:
      probability: 1.0
# traceID and spanId are predefined MDC keys - we want the logs to include them
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"