server:
  port: 9000
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
      git:
        uri: https://github.com/Samnang-An/MircoServices_Example/configuration
        username: Samnang-An
        password: